### PR TITLE
added sphinx doc support

### PR DESCRIPTION
**Pull request by iamrajhans**
Sphinx doc support. #9

### CODE REVIEW

**Comment by huxuan** [comment]
Hi @iamrajhans, thanks for your contribution. The PR looks almost good to me, but there are two general concerns.
Firstly, from my point of view, sphinx support mostly focus on docstrings change (current docstrings mostly follow Google Python Style Guide) rather than adding sphinx common components. Do you have any plan to change the docstrings?
Secondly, as you have signed the contribution license, a kindly reminder is that all copyright should belongs to Microsoft and also be careful about other metadata like version number.

**Comment by iamrajhans** [comment]
Hey @huxuan i don't think of changing the  doctoring right now.

**Comment by huxuan** [comment]
Only add sphinx support is not the target of #9. We need to revise all the docstrings in sphinx style.

**Comment by iamrajhans** [comment]
okay @huxuan can i know what are the new changes need to be done.

**Comment by huxuan** [comment]
We need to modify all the docstrings and make it be able to generate the docs successfully.

**Comment by huxuan** [comment]
Close as there is no further updates.

**Pull request closed without merging**
