### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by getdakeen**
Edited sample labels. (Did I do this right, in terms of how I did the forking, branching, and pull request?)

### CODE REVIEW

**Comment by huxuan** [comment]
**Yep, the workflow is definitely right.**
But seems all the EOL (end of line) [1] have been changed, so this PR changes all the content of the file.
I am not sure what caused this problem, may I know the editor you are using for editing?
In case you need any help, feel free to ping me on Skype.

[1] https://en.wikipedia.org/wiki/Newline

**Comment by getdakeen** [comment]
Thank you and, once again, really sorry about the trouble. I'm using Geany ,version 1.29. I'm not sure what happened. I only updated the text of the label variables, saved the .py files, and then tested the sample to make sure I didn't break it while making the changes. Perhaps I should use Visual Studio, instead? What editor does the dev team use for Python?

**Comment by getdakeen** [comment]
I've just thought of another possible cause for this problem. To start this process, I created a fork on my account, and then a new branch on that fork, and then I cloned the files to my machine. I updated them locally, and then used the "Upload files" button on GitHub to upload them to the branch. Then I made the pull request. Does uploading the files like this clobber the original ones and make it seem like I've changed everything in these files?

**Comment by huxuan** [comment]
Hi @getdakeen, uploading might be the cause of the problem. Do you have experience to use `git` command? Or maybe you can have a try of the GUI version provided by github [1]. But if you will only change the labels, which means you do not need to test the functionality, I think you can directly edit on github website. Take `panel_detection.py` as example [2] (note about the repo account and branch name), there is an edit icon (a pencil) on the top right corner.

[1] https://desktop.github.com/
[2] https://github.com/getdakeen/Cognitive-Face-Python/blob/face-tutorial-label-edits/sample/view/panel_detection.py

**Comment by getdakeen** [comment]
OK, thank you! I haven't used the **git** command before, but I will read about it and try it out. 

I've tried the GitHub online editor and found it rather limited and even problematic at times. 

Please disregard this pull request, as well as the previous ones for this sample. I will close them and send another one when I get it right.

**Comment by huxuan** [comment]
Thanks for your patient. If you need to learn the basic usage of `git` command, you may have a try here [1]. I have little experience on both github online editors and github desktop (the GUI version of git command), but they are designed to be an alternative choice other than git command. So feel free to use it if they meet your need. Another tip is that, when you are going to send a pull request, you can brief check the difference before really sending it, that will avoid some simple mistakes. Again, in case you have any problem, feel free to reach me.

[1] https://try.github.io/

**Pull request closed without merging**
